/*tn.h - token에 관한 정의, errorTypes에 관한 정의
* programmer - 김서영, 김효진, 서지원, 손효원
* date - 
*/

enum tokentypes {
	TIDENT, TPLUS, TMUL, TMOD, TMINUS, TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE, TMOD, TASSIGN,
	TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN, TNOT, TAND, TOR, TEQUAL, TNOTEQU, TLESS, TGREAT,
	TLESSE, TGREATE, TINC, TDEC, TLPAREN, TRPAREN, TCOMMA, TSEMI, TLBRACE, TRBRACE, TLBRACKET, TRBRACKET, TNUMBER, TREALNUM,
	TCOMMENT, TLINE, TSEPARATOR, TBQUOTE, TSQUOTE
};

enum errorTypes {
	noerror, illsp, illid, overst, overfl, illch
};
